INSERT INTO T_USER (USR_FIRST_NAME, USR_LAST_NAME, USR_IS_ACTIVE, USR_EMAIL, USR_PASS_HASH, USR_DEPT, CREATED_BY, VERSION)
	VALUES ('Zakaria', 'DRISSI', 1, 'duc.nguyen@gmail.com', 'azeaze-azeaze-azeaze-azeaz', 'STRUCTIS', 'Z.DRISSI', 0);
	
INSERT INTO T_USER (USR_FIRST_NAME, USR_LAST_NAME, USR_IS_ACTIVE, USR_EMAIL, USR_PASS_HASH, USR_DEPT, CREATED_BY, VERSION)
	VALUES ('Hicham', 'Ismaili', 1, 'h.ismaili@gmail.com', 'azeaze-azeaze-azeaze-azeaz', 'STRUCTIS', 'Z.DRISSI', 0);
	
INSERT INTO T_USER (USR_FIRST_NAME, USR_LAST_NAME, USR_IS_ACTIVE, USR_EMAIL, USR_PASS_HASH, USR_DEPT, CREATED_BY, VERSION)
	VALUES ('Abdelouahed', 'Ben Tayaa', 1, 'a.bentayaa@gmail.com', 'azeaze-azeaze-azeaze-azeaz', 'STRUCTIS', 'Z.DRISSI', 0);
	
INSERT INTO T_APPLICATION(APP_ID, APP_NAME, APP_DESCRIPTION, APP_HASH_ID, CREATED_BY, VERSION)
	VALUES(1, 'MobOps', 'Lorem ipsum bla bla', 'erer-erer-ere', 'Z.DRISSI', 0);
	
INSERT INTO T_APPLICATION(APP_ID, APP_NAME, APP_DESCRIPTION, APP_HASH_ID, CREATED_BY, VERSION)
	VALUES(2, 'EDoc Mobile', 'Lorem ipsum bla bla', 'erer-erer-ere', 'Z.DRISSI', 0);
	
INSERT INTO T_APPLICATION(APP_ID, APP_NAME, APP_DESCRIPTION, APP_HASH_ID, CREATED_BY, VERSION)
	VALUES(3, 'Watt Mobile', 'Lorem ipsum bla bla', 'erer-erer-ere', 'Z.DRISSI', 0);
	
INSERT INTO T_APPLICATION(APP_ID, APP_NAME, APP_DESCRIPTION, APP_HASH_ID, CREATED_BY, VERSION)
	VALUES(4, 'Nomadis', 'Lorem ipsum bla bla', 'erer-erer-ere', 'Z.DRISSI', 0);
	
INSERT INTO T_USER_APPS(USR_ID, APP_ID)
	VALUES(1, 1);
	
INSERT INTO T_VERIFICATION_TOKEN(TKN_VALUE, TKN_EXPIRY_DATE, USR_ID)
	VALUES('c0c949a9-ceff-4e42-b80f-2479d911657f-127736', '2090-01-01', 1);
	
INSERT INTO T_VERIFICATION_TOKEN(TKN_VALUE, TKN_EXPIRY_DATE, USR_ID)
	VALUES('c0c949a9-ceff-4e42-b80f-2479d911657f-127789', '2010-01-01', 2);
	
INSERT INTO T_VERIFICATION_TOKEN(TKN_VALUE, TKN_EXPIRY_DATE, USR_ID)
	VALUES('c0c949a9-ceff-4e42-b80f-2479d911657f-127036', '2021-01-01', 3);
	
INSERT INTO T_MK_USER(MKU_ARGOS_ID, MKU_USERNAME, MKU_FIRST_NAME, MKU_LAST_NAME, MKU_EMAIL, MKU_PASSWORD_HASH, MKU_IS_ENABLED, MKU_PWD_RESET_DATE, CREATED_BY, VERSION)
	VALUES('0000099246', 'z.drissi', 'Nguyen', 'DUC', 'duc.nguyen@gmail.com', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 1, '2010-01-01', 'Z.DRISSI', 0);
	
INSERT INTO T_MK_USER(MKU_USERNAME, MKU_FIRST_NAME, MKU_LAST_NAME, MKU_EMAIL, MKU_PASSWORD_HASH, MKU_IS_ENABLED, MKU_PWD_RESET_DATE, CREATED_BY, VERSION)
	VALUES('a.bentayaa', 'Abdelouahed', 'Ben Tayaa', 'bentayaa@gmail.com', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 0, '2010-01-01', 'Z.DRISSI', 0);